---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: eloup-web-secret
  namespace: eloup
spec:
  encryptedData:
    APP_SESSION_SECRET: AgCZSJxmJC0k8292Ob9iR2gTd7E+XomsRiqlIBUQg1YwfPBAk6iMvMRqH3Wp6fiEWBSxK0duWXeBO4wzP03aC3wjl6a8SUrfCBCIVAuLpVZikfRybJLN+CBNwGTnwYiR8G51ync1caB203vA/Z5TbIuL01BNlfq2DnA3phGfh6cMH+HfAp83CKqmEiCRTOzNTiF6nxXPJ6QHqvw8/yHphEOcDx3SuWvMfEUugdlxweUSpQ67xZ1edduYOcv6dwHKaPQgDoN3bsu3vI949fJUUeW5sWaLelKV2dISVHki5LuEu5IjvpvZy3KLCXU80VrklJR5OPashlxpX8QlKo93GZnQa9GlKhJYJYP00EzWgagHOQKt6axC7OEHzilwW68ZNYYb7yY8Fu7l/z8TX+ONURBAMTYBq9fVHQQDlN6z7GqSsUZZLeMQ5jIR3cefsOR/ZcYv+Lm8Qe67A4WSllfQuwMXg/ijvQ4uCuX/Rk9nPPVeuC8eUyaDoQRzl2ixiME4t5vaVfZlDN0blQ2Lfu8viTG7D0nPG8ATdgV8bhmJfkj5RaKGta0eAV7x908CDU17I6fL1ZBUrq2Ie25rGKvLU2ktd4VaO6Bh/ICxJKQggtmDSOabD3gcHhUj3wiBEhykXt9+wPnxHdMC9PtlFJakAj7wCeBUIgllfnBzNxa1zpm6Fg3IX6nMduoCSlStSgsxXCBqUvzKztcyzv3FE5bZ5lMG15A96g+Z1lw93ZPrsPLej9Sbtw9EjpD4jF8f
    DISCORD_CLIENT_SECRET: AgCJseCcFnmdsdqreK/Pfq/NDO7Vc0EMtRg/grMQ7BQGtTatUjjduBfOpzAx38oyWVnmQjbHO9N813ASY7Vv5dH08LG9RncHqjb8be42NWQoaPij2ixHdlM3zIZgFDmMDKZyl3as5VdTyCiyyc69j8/n4vL/BZ8mlHW7Gkf6+eEF71lPHZyBGOPxUTl1tlN0glGi6cXatQJVi6MU027RU+QmDoLW6bAz1SyB8QzWkEFnG17OQrdkfjmL2yM2HrAFJr/GOmqRbiOi2sIieI7zXfyAvFbAyGKg8k4+PnPS8UIfqYve0F3Ow+A20ghtpuQhdK5hKVzoVqK2yRX2LJrSxI/pGfQkkkC8e1KsfLTa7VNcK3Wre56LOUk2LyGg3TEbQp8mJ0dP/hKYQavVm6iOXCp3gAHlGYJlSx+1Bda+niV+H4lBuJ8/t+KrUis7Pzjxq6YBsuHSxPyhrP+j/Tu98EDxwF9lkJ5SC9qwYCJZs8ZP2JsGyX0LLmdKoiYsVijkRsqPKr/dvsXkE/Q/UwbK1y5XaphQKj3FyTmLm5+58YzQk1SHaX3gUodSI2qrU3ZLj0ziLLa6H8KDUZVgKNSJLi1ccfQ1YObF34qsBtf97vM9hVMSfDr3fFcSIDXfxsAlEJ2ZqBLTJ6PAlVY7AH7AVZS41GBDlBQfUxAGWLNv8yuWYKB+5aJSbV/btiWTOIKKlUEEDQnBQP98Qh8TgY2OUVRiA5KAbQzNKueRIJi5UX/9dQ==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eloup-web
      name: eloup-web-secret
      namespace: eloup
    type: Opaque
