---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: eloup-web-secret
  namespace: eloup
spec:
  encryptedData:
    APP_SESSION_SECRET: AgCaDTX6eSQMzCoevOxMyNFlh1QftGpv0hbaeFlGcUJw0V4btQebo9FLOyilbgzBfbwOmny+sKZyaMMqZ2+lgLmwoT702BzqbxK75goRuvfakEI7M5lY31+PfQwUfuEmThDY/jOmqKDy/O9UOQX+S/AiDG5HoyGdrbREft3xCTqDpOPxS/lnqtvAYvQeQrlfiPDfceImPxRndvMM9wwP88NCqcRDa07PM4mSY9Pu/S7p/QHnZjy+aZRMxwnwWUqWeqmqT4mwUlyxKM/6N3UoJQ44KVcvh2HwHKXWq1Jj0kkz7hYU8P5h9Odq1w9YW1HeDTycXEJe4j+ljK+aDEO3k0mR/KQvZUje7OOlpz/8e9BXZPTW01HU5cnUMhoSS0vlx8sAYQh4A8Dpl66ZuQD7rxaRQKBrpZvG4UOs5yqLsUmw1oEymMoKv63ewUrx7CX9rQ+M9kDl0hhqeX5z9j6XSrcwpqFyluTxhXECSKN3+w+dhB+tNbQ1cr7wmqlPMNVo0Noq40fa9Yx3D/h5OL/dnpg6GY2IThuczf4Dc5DDTz1ngECpaTW5DyA2hqG8fmpzQdlOsYNP3z0+kokRkOlsuDB892jCfJcYSOUv7DAQNv/cNal9B8CTXRHNd/4Zt0Pqx8BIqpAeRro8PcqGWTbAV1nUOmq9LahRPBF5p9K99SJ4dqQ75nL52yJGmMoqWMi9jQ4OhxjBGlNb8zGNLzZaOPm2hgereePTTqxe4ikPFmwZOIGibqzMeIOL/oR5
    DISCORD_CLIENT_SECRET: AgBFbk0SdWlp7QlvNAjYPXlzgU+Ef39o775I/NCTv0VhOwC0ZrVjONByHM0r0tOYbkfhFHIdnvBNgWDfrZmEBoP5+P4CiVCy26w7r/9eBpDHDj1tk/h+9HKRjv1nyEI2WMHv32j/qScO0D8BF+JrBN+iqyf1XFfIXIo8srz/UGNjyLvGNrKoRN0wDC4ZgbjXQOMKevb04wmI0b0VxMcpMBn9IocifuDtN21vQJYjt50tbjTy6AZN8UIUCmw8nDyFZEgf5I1Z1YVL5kl2VNj/o8LEIeEfG7JLgcxPmRA1uIG6/B9zLH6JKXOaoe6sGBFk2xLIUlO993bS3ZGqWhThN77iyAUv/47UMdUk3mK4VEBywOyAwEuaSTHSrLvBCzFn4w7+5tgeiW+mZTYAvM8+oiHSS0O7fe31c9Aq2aUeUoUnIKReZFsrSJvyj3czJ33i5QgtZDeYT2VTsmIsFalT0NMET6c6vOGWuAfF/nb9sYSv08TFmSTyHwE6zW+IPmA8ENWId8BSuULi/kufoPW+YiLBZTpGedNetAEZQEY9J1WlODIGfM69zKBL68ScaCHxC4hiNjfHnuLLzxMQTnD+MzP8z62fw4mBYOeFF42u2Lm8w0pN6DJQO7pl02r9zS++qwMwo/1e1ye8HPw/upt0C1d3oZUOaWqUOdMyH8zjZugaGqjWTbqvyr8+9r6hpQL4IAdXMfMwtghrMLjsruxPC/+Sh8AmoYYbPwAUPLf3ZURgTg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eloup-web
      name: eloup-web-secret
      namespace: eloup
    type: Opaque
