---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: eloup-web-secret
  namespace: eloup
spec:
  encryptedData:
    APP_SESSION_SECRET: AgCENYeGrf9gB7s9SY0thumqEqtTlTdbqqafBLJujL8QP0/TErx7fkIt656wBceW6Qu/fMdXywayOWoleh/qPCAm1wRTDTS8bdtnlAscjGcwFblm+HneSzE1Ifymm7Mfdz1tB39zMIBsDqPPE81oU//5pPwi4oS9USaSRH0Kb2/JjURRQRZygRK1UX0uTshPoUig6V6TLaKaOatHRNrPN/FPiV83kq0Mu/i+5cIeMdX1mqcOwNAeSD7RRohWqHZi4LFERrz97EBc6DJcecS9qNORivNp+py976+SUegLa6YghOXfvoXCt7uhN6o9fjY583Pb1PqdHbLTRXv8RtkBpRbIp4N+4yg+iM+v2uMowRDgpMp+TRlsdgfjEzhm+fpKnGEFaSVyVmLRvNOBJy9vYylZqOrTJVCaHICUhbJF4mv5j9ESwvj1C8aPm8VZqpWLVBft9v3lrbYFl9UjWKU9BfAx9CuSF4f7XnpPZI5r4NIRSg6Y5n2pUiS1NpVLZdRm5FgiazE6fU6S2aMhgHPiLj4JNH7pMDGlqAg1bHOvD2BcsbQKyj0FN7D7ufl4AP5Wlk9HQX/8fBCPdX0LB8P17BDhJaYU5TzGFPCiNjK0QbLDp/yIwVYyOp+KgfSoCh0bYDqJhN4Or0uL/cb5W2g8I8lHuVasJIn1qQVhNZbvbeR5J2Q31cbo+N2btC0BarYzoWsFJ61TSBagrb7u/lEqe+PixGkg/X8DGHSKjTvA0sg1nD7EEKUKmPkvnpe8
    DISCORD_CLIENT_SECRET: AgC6lw2jwpI4/g8+epX9PyiWNi3X7+pDc68D/tMzCIecpKLMWJHADEeLZo4jx0h7vPGBe7NlSndOk5kmYZxMY4Y6Zwv3iSOZOYa7c8GKNTwbRNe2EXDGe500sCt4CILR62ks/P2CK9hNlAPFtvzsaTKBzoBJxWPgvuAWW4NmB454+6uxO8Srs2bnUT6vY1uvpVqNlZIUHEvdrc5WliHYFtTbSLE7k2bR6DVE1A1+i05JMx6wgFK3uoQybLa/qHtrDwxqtrXIwbThwtpMlSxtY3fsbhXBUdMjGOfuOHy5Vo+LCiitZjVsVM37SQrWo90uUpjNbjdhKis2jrXpDPXZeZPEO1msT7ULJFijAeCT8kVbOy6+bOSadTXW7AJEgSGf7DzDYEWV4r7assckducjV3Iwa/Ne2MY3q1c20+gE3Mnj8Du8rxlrw0j82maK3E2rk+P/kbz0z76d348kLMRVNifFn9Gmmxzj9r4X/vnqjfaciKGmr7ykifHLwRrWiZNa+bpKTz2hDtIcIBlhMxwCP1Glirvg6AOkVyuFdvvl+7P9sMi4XFqkXFu3S//M1hvY07bvfGrI/SVw2cUUqsBzBTzsxT4gT1EwWJVG/LW2Cho2JuXsJTroySYCAhXgxz3jmrg/egPoCIGE86mJ9j7TBree8sie1/3WLPC6MF0TTgLhuVEuZA5Tlo85FXgnl178dKSFtwwKO8YyOZNj9R1OqftgUh23eRtc7tqjSaSlQ67XSw==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eloup-web
      name: eloup-web-secret
      namespace: eloup
    type: Opaque
